const breedList = [
    {"name":"Chinese Crested Dog"},
    {"name":"Chow Chow"},
    {"name":"Clumber Spaniel"},
    {"name":"Cocker Spaniel Americano"},
    {"name":"Cocker Spaniel Ingles"},
    {"name":"Collie"},
    {"name":"Dachshund"},
    {"name":"Dalmata"},
    {"name":"Deerhound"},
    {"name":"Dobermann"},
    {"name":"Dogo Argentino"},
    {"name":"Dogue Alemão"}
    ,
    {"name":"Elkhound Noruegues"},
    {"name":"Fila Brasileiro"},
    {"name":"Flat Coated Retriever"},
    {"name":"Fox Terrier"},
    {"name":"Fox Terrier Brasileiro"},
    {"name":"Foxhound Americano"},
    {"name":"Foxhound Ingles"},
    {"name":"Golden Retriever"},
    {"name":"Greyhound"},
    {"name":"Hamster"},
    {"name":"Husky Siberiano"},
    {"name":"Irish Terrier"},
    {"name":"Jagdterrier"},
    {"name":"Keeshond"},
    {"name":"Komondor"},
    {"name":"Labrador"},
    {"name":"Lapao"},
    {"name":"Leonberger"},
    {"name":"Lhasa Apso"},
    {"name":"Lulu Da Pomerãnia"}
    ,
    {"name":"Maine Coon"},
    {"name":"Malamute Do Alasca"},
    {"name":"Maltes"},
    {"name":"Mastiff"},
    {"name":"Mastim Bordeaux"},
    {"name":"Mastim Dos Pirineus"},
    {"name":"Mastim Napolitano"},
    {"name":"Miniatura Bullterrier"},
    {"name":"Miniatura Dachshund"},
    {"name":"Miniatura Pinscher"},
    {"name":"Norwich Terrier"},
    {"name":"Old English Sheepdog"},
    {"name":"Papillon"},
    {"name":"Pastor Alemo"},
    {"name":"Pastor Belga"},
    {"name":"Pelo Curto Brasileiro"},
    {"name":"Pequines"},
    {"name":"Persa"},
    {"name":"Pinscher"},
    {"name":"Pit Bull"},
    {"name":"Pointer Alemão"},
    {"name":"Pointer Ingles"},
    {"name":"Poodle Gigante"},
    {"name":"Poodle Micro"},
    {"name":"Poodle Standard"},
    {"name":"Poodle Toy"},
    {"name":"Pug"},
    {"name":"Puli"},
    {"name":"Retriever Do Labrador"},
    {"name":"Rhodesian Ridgeback"},
    {"name":"Rottweiller"},
    {"name":"Sabujo"},
    {"name":"Sagrado Da Birmânia"}
    ,
    {"name":"Saluki"},
    {"name":"Samoieda"},
    {"name":"Sao Bernardo"},
    {"name":"Schipperkee"},
    {"name":"Schnauzer"},
    {"name":"Schnauzer Ano"},
    {"name":"Schnauzer Gigante"},
    {"name":"Scotch Terrier"},
    {"name":"Scottish Terrier"},
    {"name":"Setter Gordon"},
    {"name":"Setter Ingles"},
    {"name":"Setter Irlandes"},
    {"name":"Shar-pei"},
    {"name":"Shih- Tzu"},
    {"name":"Siames"},
    {"name":"Silk Terrier"},
    {"name":"Skye Terrier"},
    {"name":"Slughi"},
    {"name":"Spaniel Breto"},
    {"name":"Spitz"},
    {"name":"Springer Spaniel"},
    {"name":"Srd Canino"},
    {"name":"Srd Felino"},
    {"name":"Staffordshire Bull Terrier"},
    {"name":"Tenerife"},
    {"name":"Terra Nova"},
    {"name":"Vizsla"},
    {"name":"Weimaraner"},
    {"name":"Welsh Corgi"},
    {"name":"Whippet"},
    {"name":"Wolfhound Irlandês"}
    ,
    {"name":"Yorkshire Terrier"}
    ]

export default breedList